 pipeline:
  setup:
   image: hbb:salmon_build_new
   commands:
    - echo "Starting build"
    - ./.drone/build.sh
  test_indexing:
   image: hbb:salmon_build_new
   commands:
    - echo "[Testing quant]"
    - ./.drone/test_quant.sh 
   volumes:
    - /mnt/scratch6/avi/data:/mnt/data
    - /mnt/scratch6/salmon_ci:/mnt/ci_res
  copy_build:
    image: hbb:salmon_build_new
    commands:
     - echo "[Packaging binary]"
     - ./.drone/copy_build.sh
    volumes:
     - /mnt/scratch6/avi/data:/mnt/data
     - /mnt/scratch6/salmon_ci:/mnt/ci_res
  notify_gitter:
    image: plugins/gitter
    commands:
     - echo "[Notifying gitter]"
